### ISSUE TITLE
[Feature request]: add commands

### ISSUE THREAD

**Issue by lopi-py** [alexghergh/nvim-tmux-navigation#10]
would be nice to have commands like `TmuxNavigateLeft`, `TmuxNavigateRight` and so on. neovim supports adding commands by `vim.api.nvim_create_user_command`

**Comment by alexghergh** [comment]
Hey, thanks for opening a feature request!

I will look into it in the upcoming week! The problem for now is backwards compatibility. The functionality you mention was only recently introduced in Neovim 0.7.0 if I'm not mistaken. I want to be extra careful with such features, in order not to leave some users behind.

**Comment by alexghergh** [comment]
Heya, sorry for taking so long with the issue.

Commit 959fcb4a020fde240e12a347ad3f4f2f17d9b525 introduces the commands! Now you can do `:NvimTmuxNavigateLeft` and so on. Hooray!

Closing the issue, let me know if there's something else I can help with.
