### ISSUE TITLE
not work from tmux to nvim

### ISSUE THREAD

**Issue by bj-edward** [alexghergh/nvim-tmux-navigation#19]
I am able to switch from nvim to tmux, but not from tmux to nvim. I have set the following:

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

**Comment by bj-edward** [comment]
working well now. It seems not work ~/.config/tmux/.tmux.conf, chang to ~/.tmux.conf.

**Comment by alexghergh** [comment]
Hey, If you want to follow XDG directories, you must put the tmux.conf file into `~/.config/tmux/tmux.conf` (notice there is no `.` before tmux.conf). That's probably why it didn't work for you.

Closing, feel free to re-open if necessary.
