### ISSUE TITLE
Problem with swtiching panes

### ISSUE THREAD

**Issue by imli700** [alexghergh/nvim-tmux-navigation#8]
I'm very new at all this linux stuff so please forgive my incompetence. The following is a screen shot of of my configs: The top is the tmux config, the bottom left is the neovim keybind settings and the bottom right is my init.lua for neovim.

![secondary memory heirarchy](https://user-images.githubusercontent.com/76049491/186556687-b5c8eb92-4d6c-4c7b-9d7b-f774d2d9041b.png)

My issues is that I can switch between neovim panes created inside neovim itself using the default keybinds (<C-h/j/k/l>) and I can also switch to panes outside of neovim (bash, for example). However, once I do this (i.e focus on a pane outside of neovim), the keybinds no longer work and I have to use the default tmux keybinds i.e. those prefixed by <C-b> and followed by the directional keys, to swith around panes. The extension's keybinds work again once I switch to a neovim pane.

In the screenshot above, the top and bottom panes are seperate tmux panes. While the two on the bottom are split via neovim. So I can move between the bottom two using <C-h/j/k/l>, but once I focus on the top, the keybinds stop working and I have to use Ctrl + b followed by the directional keys to go back to the bottom panes.

**Comment by alexghergh** [comment]
Hello,

And welcome to the Linux world, a fantastic world of opportunities and freedom.

Looks like you managed to get the issue fixed? Do you mind writing in short how you solved it, or what the problem was? It would also help me debug similar issues in the future.

Thank you and have a fun time Vim-ing!

**Comment by imli700** [comment]
Hi, I tried

**Comment by imli700** [comment]
Sorry, it was probably a mistake from my side. I removed the pugin and redid the installtion process and it worked

**Comment by alexghergh** [comment]
Not a problem. I'll close the issue then.
